import random
def get_health_tip():
    health_tips = [
        "Drink at least 8 glasses of water daily 💧.",
        "Exercise for 30 minutes a day to stay active 🏃.",
        "Eat a balanced diet rich in fruits and vegetables 🍎🥦.",
        "Get 6-9 hours of sleep each night 😴.",
        "Practice deep breathing or meditation for stress relief 🧘.",
        "Wash your hands regularly to prevent infections 🧼.",
        "Take breaks from screens to reduce eye strain 👀.",
        "Stay connected with friends and family for mental well-being ❤️.",
        "Limit sugar intake to maintain a healthy weight 🍭🚫.",
        "Stretch daily to improve flexibility and prevent stiffness 🤸.",
        "Use sunscreen to protect your skin from harmful UV rays ☀️🧴.",
        "Avoid processed foods and opt for whole foods instead 🥗.",
        "Drink herbal tea for relaxation and digestion 🍵.",
        "Get at least 15 minutes of sunlight daily for vitamin D 🌞.",
        "Maintain good posture to prevent back pain 🏋️.",
        "Reduce salt intake to keep your blood pressure in check 🧂🚫.",
        "Include probiotics in your diet for a healthy gut 🥛.",
        "Stay active throughout the day—avoid prolonged sitting 🏃‍♂️.",
        "Eat slowly and mindfully to aid digestion and prevent overeating 🍽️.",
        "Incorporate strength training into your workout routine 💪.",
        "Chew your food properly to improve digestion 🦷.",
        "Get regular health check-ups to catch issues early 🏥.",
        "Use blue light filters to protect your eyes from screen strain 📱.",
        "Avoid smoking and limit alcohol consumption 🚭🍷.",
        "Laugh more—it reduces stress and boosts your mood 😂.",
        "Always warm up before exercising to prevent injuries 🔥.",
        "Include fiber-rich foods to improve digestion and heart health 🍞.",
        "Set a consistent sleep schedule to regulate your body clock ⏰.",
        "Swap sugary drinks for water or fresh juices 🍹🚫.",
        "Practice gratitude to boost mental well-being 🙏.",
        "Use stairs instead of elevators for extra movement 🏢⬆️.",
        "Maintain a healthy work-life balance for reduced stress ⚖️.",
        "Limit caffeine intake, especially in the afternoon ☕🚫.",
        "Read labels on food products to avoid hidden sugars and additives 🏷️.",
        "Cook more meals at home for better nutrition 🍳.",
        "Drink warm lemon water in the morning to aid digestion 🍋.",
        "Try to get at least 10,000 steps a day 🚶‍♂️.",
        "Opt for organic and pesticide-free foods when possible 🌿.",
        "Listen to your body—rest when needed 🛌.",
        "Use natural light in the morning to boost energy ☀️.",
        "Consume omega-3 fatty acids for brain and heart health 🐟.",
        "Keep a gratitude journal to cultivate positivity 📖.",
        "Eat a protein-rich breakfast to stay full longer 🍳.",
        "Take a digital detox regularly to refresh your mind 📵.",
        "Avoid eating late at night for better digestion 🌙.",
        "Use a standing desk or take frequent breaks if you sit all day 💺.",
        "Drink plenty of water before meals to avoid overeating 🚰.",
        "Include nuts and seeds in your diet for healthy fats 🥜.",
        "Engage in hobbies to relieve stress and improve creativity 🎨.",
        "Laugh and smile more—it strengthens your immune system 😄.",
        "Plan your meals ahead to make healthier choices 🗓️.",
        "Take deep breaths when feeling anxious to calm your nerves 🌬️.",
        "Listen to relaxing music to lower stress levels 🎵.",
        "Practice self-care regularly—your well-being matters 💆‍♀️.",
        "Cut down on fast food and cook fresh meals instead 🍔🚫.",
        "Try intermittent fasting for better metabolism ⏳.",
        "Swap unhealthy snacks for fruits or nuts 🍌.",
        "Drink enough water during workouts to stay hydrated 💦.",
        "Limit exposure to pollution and toxins for better lung health 🌫️.",
        "Add turmeric to your diet for its anti-inflammatory benefits 🌿.",
        "Get enough magnesium to support muscle and nerve function ⚡.",
        "Spend time in nature to reduce stress and improve mood 🌳.",
        "Massage your hands and feet for relaxation and circulation 💆.",
        "Eat dark chocolate in moderation—it’s good for the heart 🍫.",
        "Don’t skip breakfast—it jumpstarts your metabolism 🍽️.",
        "Alternate between hot and cold showers to boost circulation 🚿.",
        "Wear comfortable shoes to prevent foot problems 👟.",
        "Keep your bedroom cool and dark for better sleep 🌙.",
        "Laughing increases endorphins and boosts happiness 😂.",
        "Keep a reusable water bottle with you to stay hydrated 🚰.",
        "Be kind to yourself—self-love is essential ❤️.",
        "Reduce food waste by planning meals efficiently 🥡.",
        "Drink coconut water to replenish electrolytes 🥥.",
        "Use essential oils like lavender for relaxation 🌿.",
        "Eat a handful of almonds daily for heart health 🌰.",
        "Stand up and stretch every hour if you work at a desk 🏋️‍♂️.",
        "Wash your fruits and vegetables thoroughly before eating 🥕.",
        "Try yoga for flexibility and mental clarity 🧘‍♀️.",
        "Cut back on sugary cereals—opt for whole grains instead 🥣.",
        "Stay away from toxic relationships for emotional well-being 🚫.",
        "Limit fried foods to maintain a healthy weight 🍟🚫.",
        "Use portion control to avoid overeating 🍽️.",
        "Always carry healthy snacks when traveling to avoid junk food 👜.",
        "Stay optimistic—positivity improves overall health 😊.",
        "Chewing sugar-free gum can improve concentration and digestion 🍬.",
        "Incorporate garlic into your diet for immune support 🧄.",
        "Read books to keep your mind sharp and reduce stress 📚.",
        "Eat at least five servings of vegetables daily 🥗.",
        "Don’t hold your phone too close to your eyes 👀.",
        "Reduce plastic use for both health and environmental benefits 🌍.",
        "Drink chamomile tea for relaxation before bed 🍵.",
        "Listen to your hunger cues—eat when hungry, stop when full 🍽️.",
        "Take a probiotic supplement for gut health 🦠.",
        "Use a humidifier in dry climates to prevent dry skin 🌫️.",
        "Keep your workspace clean to prevent illness and boost focus 🧼.",
        "Choose stairs over elevators whenever possible 🏢.",
        "Cut down on red meat and eat more plant-based proteins 🌱.",
        "Journal before bed to declutter your mind 📝.",
        "Try tai chi for balance and relaxation 🥋.",
        "Acknowledge and express your feelings—it’s healthy 😊.",
        "Swap unhealthy desserts for dark chocolate or fruit 🍓.",
        "Declutter your home—it reduces stress and enhances well-being 🏡.",
        "Be patient with yourself—progress takes time ⏳.",
    ]
    return random.choice(health_tips)